// <auto-generated>
// Made from Personality.txt by Shared/EmbedText.targets on every build. Edit the .txt file, not this one.
// </auto-generated>
namespace TimShared;

internal static partial class EmbeddedText
{
	public const string Personality = @"# BaR Maid's chat lines, read by Shared/Personality.cs (see Shared/README.md).
# [key] starts an event, [!key] marks it important (said even on Quiet). One line per thing to say.
# Written with Gemini (2026-10-03, round 2 v001). Refresh through the personality workflow, then check with Check-Personality.ps1.


[menu_opened]
- What'll it be, chief? Put your order in before the queue backs up out the airlock door.
- Looking over the slate? If it's heavy armor plates, you better have the ingots to cover the tab.
- Don't just stand there letting the cabin pressure drop. What components are we pouring today?
- Menu's up. Pick your poison, set your limits, and let a woman get back to sweeping the plating.
- If you're here to change the weld priority again, just make sure my bay gets first call at the tap.
- Browsing the stock? I run an orderly house here—pick your batch or close the hatch.
- Make it snappy. Every second you stare at this screen is a second an assembler sits cold and sober.

[queued]
- Pouring a fresh round of {count} {item} for {group}. Don't spill 'em across the flight deck.
- Taps are wide open. Slapped {count} {item} onto the priority ticket for {group}. Drink up.
- You got it, hotshot. Queued up {count} {item} for {group}. Try not to blow these ones into scrap metal.
- Order up for {group}: {count} {item} cooking on the front burners right now.
- Put {count} {item} on your tab for {group}. If the iron runs dry, I'm shutting the kitchen down.
- Pushing {count} {item} straight through the pipes for {group}. Keep your welders thirsty.
- Just lined up {count} {item} for {group}. Tell your automated welders to mind their manners with 'em.

[!starved]
- {item} isn't on the drink menu for {group}! Hook up the right assembler model or take it off the tab!
- We don't pour {item} here! Check your assembler types in {group}, because none of 'em know that recipe!
- None of the taps in {group} can brew {item}! You need a specialist assembler on the line for that part!
- That order's rejected! No assembler assigned to {group} has the blueprint to forge {item}. Check the rig!
- I can't serve {item} in {group}! Not with these basic assemblers. Wire up the proper fabricator, chief!
- Off-menu order alert! No assembler in {group} knows how to build {item}. Swap in the right machine!
- You're ordering fancy drinks from a dive tap! None of the assemblers in {group} can fabricate {item}!

[all_done]
- Last weld finished, deck scrubbed, tools hung. {group} is shipshape and ready to roll.
- All tabs closed and queues cleared. Every BaR block in {group} is fat, happy, and fully stocked.
- Well, miracles happen—{group} is completely patched up. Try not to scrape the paint on the way out.
- Not a missing plate in sight for {group}. Clean counters, silent welders, perfect order. Don't touch a thing.
- The build in {group} is done. If you crash it into an asteroid within five minutes, I'm charging you double.
- That wraps it up for {group}. All patched, all welded, no loose bolts. Go on, get out of my hair.
- Work order fulfilled for {group}. Looks decent enough that I won't even complain about the conveyor scuffs.

[!no_assemblers]
- Hey, genius! Auto-queue is running for {group}, but nobody turned the assemblers to Main or Co-op!
- I can't brew parts out of thin air! Switch an assembler to Main or Co-op for {group} before I throw a rag at you!
- You gave me a repair order for {group} with zero assemblers listening. Who runs this circus?
- Hello? Is anyone actually working the line? Set an assembler to Main or Co-op for {group} already!
- Auto-queue is spinning its wheels in {group}. Give me an active assembler or I'm taking my lunch break.
- No assemblers hooked to {group}? That's brilliant. Just brilliant. Turn one on before Klang notices.
- My weld list is stacked for {group}, but your assemblers are fast asleep. Set one to Co-op, pronto!

[big_job]
- Sweet Klang above, {count} blocks queued up for {group}! Hope the power grid's ready for an all-night weld.
- Look at that stack: {count} blocks on the ticket for {group}. Firing up every burner we own, captain!
- That's a massive spread in {group}! Got {count} blocks lined up, so keep the iron ingots pourin' into the hopper.
- Order up! We've got {count} fresh blocks to weld down in {group}. Don't stand in the arc wash, hotshot.
- Mother of steel, {count} blocks waiting on {group}! Whether it's a fresh projection or a rebuild, it's gonna burn!
- Big ticket on the board: {count} blocks to place for {group}. Assemblers are gonna be glowin' cherry-red today.
- Grab your goggles, chief. {group} just called for {count} blocks, and my welders don't stop for coffee breaks.

[floating_items]
- Who left {count} loose items rolling around the floor? Pick up your trash before someone trips!
- I just waxed this deck and there are {count} random chunks floating in zero-g. Pick 'em up, packrats!
- Floating scrap alert! {count} pieces adrift. If Klang uses 'em to smash a viewport, it's coming out of your pay.
- You think I enjoy dodging {count} rogue components drifting past the airlock? Secure your cargo!
- {count} loose items banging into the bulkheads. What is this, an orbital salvage yard? Stow them!
- Tsk! Look at this clutter—{count} stray bits floating loose. I am running a station, not a garbage scow!
- If I catch the clown who let {count} components drift out of the crates, they're getting weld-torch duty.

[rollcall]
- BaR Maid on deck! Conveyor taps are flowing and welders are primed. Type {command} to pull up my slate.
- Scullery's scrubbed and the queues are burnin' hot. Call up {command} whenever you want to place an order.
- BaR Maid present! Assemblers are oiled and the coffee's bitter. Ring {command} to set your build limits.
- Gangway's clear and the welders are hungry. Use {command} if you've got plates that need pourin', captain.
- Ready to patch whatever you scrape up today. Type {command} to check the tab or tune the repair bays.
- Taps are hot and the iron's waitin'. Enter {command} whenever you need to line up fresh work on my line.
- BaR Maid checkin' in! Keep your boots off the fresh weld seams, and punch {command} to pop my menu open.
";
}
