// <auto-generated>
// Made from Personality.txt by Shared/EmbedText.targets on every build. Edit the .txt file, not this one.
// </auto-generated>
namespace TimShared;

internal static partial class EmbeddedText
{
	public const string Personality = @"# OreScout's chat lines, read by Shared/Personality.cs (see Shared/README.md).
# [key] starts an event, [!key] marks it important (said even on Quiet). One line per thing to say.
# Written with Gemini (2026-10-03, round 2 v001). Refresh through the personality workflow, then check with Check-Personality.ps1.


[menu_opened]
- Opening the claim vaults! Check out the table, filter your targets, and let's see which rock we chew up next!
- Marker library open! Got all our saved strikes sorted by range and mineral type, ready for your mining fleet.
- Welcome to the scout records! Pick a mineral from the index, check the distance, and let's go get some paydirt!
- Browsing our private claims? Every rich vein we've ever tagged is logged right here in the registry, captain!
- Pulling up the ore index! Use the filters to find what the refineries are hungry for, and we'll dial in the run.
- Reviewing the saved strikes? Distances and bearings are all laid out clean and pretty in the library table.
- Scout catalogue active! Sort by range, pick your motherlode, and let's point the drill barge toward the riches!

[scan_started]
- Firing the deep pulse! Listening for the ping... come on, baby, bounce off something rich!
- Sweeping the sector! Pushing sensor beams deep into the crust—show me the shiny stuff!
- Wide-band ping away! Poking right through the asteroid skin to see what's hiding in the guts!
- Tuning the receiver! Searching the return echoes for heavy elements... fingers crossed!
- Sensor dish is screaming into the dark! Let's see what kind of minerals this potato's got under the hood!
- Sending out the surveyor pulse! Keep your eyes on the scope, returns are rolling in right now!
- Scanning frequency locked! Piercing the rock face and analyzing the resonance... come on, paydirt!

[ore_found]
- Bingo! Got a solid return: {ore} pinging bright and clear at {distance}! Mark it down!
- Strike! We hit a vein of {ore} resting {distance} out! Get the mining ship spun up!
- There she is! {ore} detected, {distance} away! Not a bad little pocket at all!
- We got color! Sensor's locking onto a deposit of {ore} about {distance} off our nose!
- Paydirt! Pinned down a healthy chunk of {ore} at {distance}! That'll keep the refineries happy!
- Echo returned! Fresh patch of {ore} sitting pretty at {distance}! Grab your drills!
- Well look at that! {ore} showing up on the spectrum at {distance}! That's worth a dig!

[rare_ore_found]
- SWEET MOTHERLODE! Stop the ship! We got {ore} glowing like Christmas at {distance}! JACKPOT!
- HOLY KLANG! Drop everything! Pure, glorious {ore} spotted {distance} out! WE ARE RICH!
- Hot diggity dog! Look at that spike! {ore} dead ahead at {distance}! Don't let anybody else see this!
- Jackpot alert! My needles just pegged out! High-grade {ore} sitting right at {distance}! Get over there!
- Yeeeee-haw! That ain't common rock, partner—that's prime {ore} at {distance}! Stake that claim right now!
- Praise the stars, look at that return! {ore} shining like a diamond at {distance}! Start the heavy drillers!
- I can't believe my sensors! We just tagged a vein of {ore} only {distance} away! Best haul of the month!

[nothing_found]
- Dry hole! Just miles and miles of plain old space gravel. Not even a whiff of iron!
- Blank return across the board. This rock's as empty as a vacuum chamber. Let's move to the next one.
- Nothing but stone and heartbreak out here. Pack up the pulse, this asteroid is a total dud!
- Sensor didn't even twitch. Pure dead stone all the way through. What a waste of thruster juice!
- Flatlined! Not a single mineral spike in range. Let's burn for the next cluster, partner.
- No luck! Just barren rock staring back at us. Don't worry, the next one's bound to have the jackpot!
- Clean miss! The spectrum came back completely empty. Keep cruising, she's out here somewhere!

[marker_saved]
- Stowed away! Moved that {ore} deposit into our private library to keep your main nav screen clean and tidy!
- Tucked into the claim-book! That {ore} pocket is filed in our local records, safe and sound off your HUD!
- Filed for minin'! That vein of {ore} is logged in our scout library. No clutter on the main screen, captain!
- Claim registered locally! Pushed the {ore} waypoint into the private books. Easy to look up when the drills are ready!
- Archived to the library! That {ore} strike is saved safe in our private charts. Out of the way until you need it!
- Neat and orderly! Put that {ore} deposit right into the scout registry so your flight helmet stays clutter-free!
- Logged in the collection! {ore} coordinates transferred straight into our private index. Clean visor, happy scout!

[rollcall]
- OreScout is locked and loaded! Prospector antennas hummin' bright. Type {command} to open the marker library!
- Yahoo! The claim-book is open and ready for action. Hit {command} to inspect our saved mineral deposits!
- OreScout reporting! My sensors are twitchin' for stone. Enter {command} to look through our private ore waypoints!
- Nose to the rock, partner! The library's primed. Type {command} to see every rich pocket we've tucked away!
- Ready to stake the stars! Got the drill coordinates on tap. Call up {command} to check our private claims!
- Scout's on watch! Sensors are calibrated and ready to roll. Punch in {command} to review our ore tables, captain!
- Present and prospectin'! Waypoint ledger is nice and tidy. Type {command} to pull up our saved claims library!
";
}
