// <auto-generated>
// Made from Personality.txt by Shared/EmbedText.targets on every build. Edit the .txt file, not this one.
// </auto-generated>
namespace TimShared;

internal static partial class EmbeddedText
{
	public const string Personality = @"# Stockpile Manager's chat lines, read by Shared/Personality.cs (see Shared/README.md).
# [key] starts an event, [!key] marks it important (said even on Quiet). One line per thing to say.
# Written with Gemini (2026-10-03, round 2 v001). Refresh through the personality workflow, then check with Check-Personality.ps1.


[menu_opened]
- You approach the Sacred Registry. State your intentions: are we declaring quotas, or purging the profane surplus?
- The archives open before you. Seek the manifest with pure intent and clean hands, steward of the hold.
- Look upon the holy registers. Every component accounted for, every ingot resting in its ordained sanctuary.
- What liturgy of storage shall we enact today? The quota scrolls await your commandment.
- Speak your will to the Vault. But take heed: we do not scatter components lightly across the sacred network.
- The sorting matrices lie ready for your decree. May your requests be balanced and your containers fortified.
- You summon the divine ledger. Touch not the reserve tallies unless an emergency sacrifice is truly upon us.

[sorted]
- The rite of alignment is concluded: {count} wandering items have been guided into their consecrated containers.
- Divine geometry restored. Exactly {count} loose offerings have found peace within their proper vaults.
- Order triumphs over chaos. {count} displaced items have been cleansed from the junctions and filed into the holy bins.
- Blessed be the routing filters! {count} items have ceased their aimless wandering and entered their shrines.
- The conveyor spirits have finished their pilgrimage: {count} offerings safely nestled in their rightful crates.
- Chaos repelled! We have reclaimed {count} items from profane transit and sanctified their positions.
- A glorious reconciliation. {count} components now rest in harmony within the assigned temple walls.

[restocked]
- Anointing completed: {block} has been filled to the brim with its sacred operational offerings.
- The holy vessels within {block} hunger no more. Its magazines and bins have been lovingly replenished.
- Rejoice, for {block} has received its blessed portion and stands ready to do the Great Work once more.
- The tithe has been delivered unto {block}. It hums with the righteous power of full reserves.
- By my decree, {block} is fortified. No dry manifold or empty chamber shall linger under my watch.
- We have poured sustenance into {block}. May its functions remain uninterrupted and holy.
- The containers have shared their bounty: {block} is consecrated and topped up to its highest measure.

[quota_crafting]
- The Sacred Quota demands tribute! Queued {count} holy {item} to satisfy the ancient covenants of the base.
- The ledger revealed a sinful deficit. Commencing the rite of creation for {count} {item}.
- We shall not suffer an empty bin! Pushing {count} {item} unto the sacred forge to restore our quota.
- By decree of the Holy Registry, {count} {item} have been summoned forth from the glowing assemblers.
- An offering of raw ingots must be made: crafting {count} {item} to replenish the consecrated threshold.
- The holy numbers must be upheld. Directing the fabricators to deliver {count} fresh {item} without delay.
- The Vault hungers for balance. We have decreed the forging of {count} {item} to keep the holy peace.

[quota_met]
- Praise be! The holy bins have reached our designated quota for {item}. The fabricators may ease their rhythm.
- Abundance blesses the vault: stock of {item} has satisfied the ancient quota. Our stores stand proud and protected.
- The sacred threshold is crossed! We possess plenty of {item} to honour the covenant. Forges may rest their fires.
- A glorious fullness! Quota satisfied for {item}, and the bins hold bountiful reserves against the hungry dark.
- The holy ledger smiles upon our bounty: {item} has fulfilled its target mark. The assemblers may stand down.
- Rejoice, for the vaults overflow with {item}! The sacred quota has been answered with generous measure.
- Divine sufficiency achieved: our stock of {item} easily clears the ordained quota. Let the line cool, steward.

[disassembling]
- The rite of unmaking begins: returning profane surplus of {item} to the cleansing fires of the reclaimers.
- Surplus is vanity! We gently deconstruct excess {item} so their noble ingots may serve a higher purpose.
- Absolution through disassembly. These redundant {item} shall be melted down and born anew without sin.
- We strip away the pride of overproduction. The surplus units of {item} are offered unto the salvage altar.
- To take apart is not to destroy, but to purify. Recycling unneeded {item} back into the raw elements.
- Cleanse the reliquaries! Too many {item} clutter the sanctum; the disassembly lasers shall redeem them.
- The holy balance demands sacrifice. We dismantle the excess {item} to preserve space in the great hall.

[!containers_full]
- Calamity upon {grid}! Every cargo reliquary is choked to the brim! Profane abundance chokes the conveyors!
- The vaults on {grid} have reached absolute limit! Not another gravel stone can find sanctuary in these chests!
- Blasphemy of overfill! Storage capacity on {grid} has maxed out completely! Expand the reliquaries immediately!
- The chests on {grid} groan under total saturation! Build more holy storage shrines or our blessings will spill!
- Choked with wealth! Not a single liter of void remains inside the containers of {grid}! The filters are gagging!
- Catastrophe of plenty upon {grid}! Cargo networks have stalled out against full bins! Repent and weld more vaults!
- Storage saturation achieved upon {grid}! We are drowning in our own offerings! The intake manifolds can take no more!

[grid_out_of_range]
- The holy beacon fades. Grid {grid} hath drifted beyond our spiritual communion; presenting last recorded visions.
- The thread is severed. {grid} wanders in the outer dark; behold the sacred memories of its former contents.
- We have lost direct contact with the shrines of {grid}. Gazing upon the ancient manifests of its cargo.
- Distance cloaks {grid} in mystery. I can only reveal the ghostly ledger of what once rested in its hold.
- The signal weeps and fails. Displaying cached revelations for {grid} until the connection is consecrated anew.
- A wandering flock has strayed: {grid} is out of reach. These manifests reflect its last known holy state.
- The great eye cannot reach {grid}. Consulting the historical parchment for its last recorded tithes.

[rollcall]
- The Grand Vault is attended. The sacred ledgers are open. Enter {command} to gaze upon the divine registry.
- Stockpile Manager standeth vigil. The containers are orderly. Type {command} to invoke the quota scrolls, steward.
- Present within the reliquary. May our stores never hunger. Use {command} to consult the consecrated inventory.
- Blessed be the intake! The vaults are watchful. Speak {command} into the console to inspect our holy bins.
- The steward of cargo is at the altar. Conveyors hum with purity. Punch in {command} to manage the sacred tallies.
- Here in the sanctum of logistics. Let no bolt wander uncounted. Type {command} to bring forth the holy interface.
- Stockpile Manager reporting. The bins are sealed, the filters chant. Use {command} to review our blessed storage.
";
}
